### ISSUE TITLE
Will be A lot of memory usage ?

### ISSUE THREAD

**Issue by sgf** [JeringTech/KeyValueStore#5]
As far as I know, Faster loads all indexes into memory, and index data tends to be large. Therefore, it will take up a lot of memory. For example, when I was running Faster's BenchMark, the memory overflowed due to insufficient memory on my computer.

My question is that the current library is a wrapper for Faster, so there will be similar problems, right? A lot of memory usage?

I am currently looking for a KV Store. It is precisely because of the limited memory and hard disk space that 20 billion keys need to be stored, but the value is not large, and the value does not need to be indexed.

my key about MaxLength 50 characters string (dynamic length).
and the value MaxLength about 50 bytes.

The production environment does not have huge memory. It is possible that the data storage area can only use memory below 512mb.

**Comment by JeremyTCD** [comment]
> My question is that the current library is a wrapper for Faster, so there will be similar problems, right? A lot of memory usage?

Hey yeah. I haven't come across any .net KV store that keeps its index on disk. 

20 billion * 50 B = 1000 GB, you might want to consider a distributed solution, e.g. Azure Blob/Table Storage.

**Comment by sgf** [comment]
> 20 billion * 50 B = 1000 GB, you might want to consider a distributed solution, e.g. Azure Blob/Table Storage.

1. We are targeting offline data(Stand-alone.).
2. The data itself is very suitable for compression.
3. Cost is very important.
